# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test -- --coverage
      - name: Install Code Climate test-reporter
        run: npm install -g codeclimate-test-reporter
      - name: Upload coverage to Code Climate
        run: codeclimate-test-reporter < coverage/lcov-report/lcov.info
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
